---
name: Tests
on:
  pull_request:
  workflow_dispatch:
jobs:
  greeter:
    uses: ./.github/workflows/test-helper.yml
    with:
      task: test-greeter
      can_continue: false
  service:
    uses: ./.github/workflows/test-helper.yml
    with:
      task: test-services
      can_continue: true
