---
name: Tests Helper
on:
  workflow_call:
    inputs:
      path:
        description: test path
        required: true
        type: string
      can_continue:
        description: continue on error
        required: false
        type: boolean
        default: false
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      # - uses: actions/checkout@v2
      # - name: Get Go version
      #   run: |
      #     echo "GO_VERSION=$(cat .go-version)" >> $GITHUB_ENV
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Run tests
        run: go test -v -race ${{ inputs.path }}
    continue-on-error: ${{ inputs.can_continue }}
