---
name: Tests
on:
  pull_request:
  workflow_dispatch:
jobs:
  greeter:
    uses: ./.github/workflows/test-helper.yml
    with:
      path: ./greeter/...
      can_continue: true
  service:
    uses: ./.github/workflows/test-helper.yml
    with:
      path: ./service/...
      can_continue: true
