---
name: Tests Helper
on:
  workflow_call:
    inputs:
      task:
        description: task name
        required: true
        type: string
      can_continue:
        description: continue on error
        required: false
        type: boolean
        default: false
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          make ${{ inputs.task }}
    continue-on-error: ${{ inputs.can_continue }}
